# Generated by Django 4.0.6 on 2022-07-20 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterlevel',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='water_tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='api.watertank'),
        ),
    ]
