# Generated by Django 4.0.6 on 2022-08-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_waterlevel_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterlevel',
            name='level',
            field=models.CharField(max_length=100),
        ),
    ]
